# Generated by Django 4.2.2 on 2023-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
