# Generated by Django 4.2.2 on 2023-06-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_profile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envia', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
